# smt needed to make fetching configs works
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

# eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"

# zipkin config
# https://www.appsdeveloperblog.com/micrometer-and-zipkin-in-spring-boot/
management:
  tracing:
    sampling:
      probability: 1.0

spring
  zipkin
    baseUrl: http://localhost:9411